### ISSUE TITLE
Error in Test the  Android  application using jenkins pipeline script.

### ISSUE THREAD

**Issue by selvakumar1994** [thyrlian/AndroidSDK#10]
Execution failed for task ':app:connectedDebugAndroidTest'.
> com.android.builder.testing.api.DeviceException: No connected devices!

**Comment by thyrlian** [comment]
Could you please tell the exact steps you've tried?  Especially the part how you launch the device.

**Comment by selvakumar1994** [comment]
pipeline {
agent {
docker {
image 'thyrlian/android-sdk'

args '-p 3000:3000 -u root'
}
}
stages {
stage('Begin') {
steps {
echo "begin"
}
}
// stage ("startEmulator") {
// steps {
// sh 'cd opt/android-sdk/emulator && emulator -avd test'
// }
// }
stage ("Checkout") {
steps {
git url: 'https://github.com/selvakumar1994/unified-code-coverage-android.git'
}
}


stage ("removelocal") {
steps {
sh "chmod 777 -Rf /var/jenkins_home/workspace/ "
sh "chmod 777 -Rf /var/jenkins_home/workspace/* "
sh 'cd /var/jenkins_home/workspace/$JOB_NAME/'
sh 'rm -rf local.properties'
}
}

stage ("Compile") {
steps {
sh "chmod 777 -Rf /var/jenkins_home/workspace/ "
sh "chmod 777 -Rf /var/jenkins_home/workspace/* "
sh "./gradlew compileDebugSources "
}
}



stage('Build APK') {
steps {
// Finish building and packaging the APK
sh './gradlew assembleRelease'

// Archive the APKs so that they can be downloaded from Jenkins
archiveArtifacts '**/*.apk'
}
}

// stage('Continous Testing - Performance Testing - Audit & Performance Metrics'){
            
//             steps{
//                 dir('report'){
//                     writeFile file:'dummyfile',text:''
//                 }
//               sh "./gradlew test"
//                 publishHTML target: [
//                     allowMissing: false,
//                     alwaysLinkToLastBuild: false,
//                     keepAll: true,
//                     reportDir: 'report',
//                     reportFiles: 'lighthouse-report.html',
//                     reportName: "Web Apps Performance Metrics Report"
//                 ]
//             }
//         }


stage('UnitTest'){
steps{
sh "./gradlew test"
// publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: '/var/jenkins_home/workspace/$JOB_NAME/build/reports/tests/testReleaseUnitTest', reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: ''])

}
 }
 stage('instrumentedTest'){
steps{
sh "./gradlew connectedAndroidTest"
// publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: '/var/jenkins_home/workspace/$JOB_NAME/build/reports/tests/testReleaseUnitTest', reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: ''])

}
 }
stage('Completed'){
steps{
echo 'Job Completed'
}
}
}
}

**Comment by selvakumar1994** [comment]
This is my error:



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:connectedDebugAndroidTest'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by selvakumar1994** [comment]
while i start the emulator via the jenkins pipeline script ,then i get the below error.


First time build. Skipping changelog.
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (startEmulator)
[Pipeline] sh
[Unittestchecking] Running shell script
+ cd /opt/android-sdk/emulator
+ emulator -avd test -noaudio -no-boot-anim -gpu off
emulator: WARNING: cannot read adb public key file: /root/.android/adbkey.pub
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: /dev/kvm is not found: VT disabled in BIOS or KVM kernel module not loaded
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Completed)
Stage 'Completed' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
$ docker stop --time=1 5da650912c7e4788fea22ce1f49688f9d7218104fd4ac503090a99ef40323ed9
$ docker rm -f 5da650912c7e4788fea22ce1f49688f9d7218104fd4ac503090a99ef40323ed9
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by selvakumar1994** [comment]
in my computer i installed docker container and kvm.

**Comment by selvakumar1994** [comment]
in command prompt i type kvm-ok in my computer then i get the below response.
INFO: /dev/kvm exists
KVM acceleration can be used.

if i type kvm-ok in command prompt in inside the container then i get "kvm not found " error.

**Comment by thyrlian** [comment]
Can you try `emulator -accel-check`?

**Comment by thyrlian** [comment]
Close as no response received.
