### ISSUE TITLE
Using this as jenkins/ssh-slave?

### ISSUE THREAD

**Issue by BlackHornet** [thyrlian/AndroidSDK#12]
Hi,

first of all, this is an awesome Image to build Android applications.

I tried to combine it in a container that is based on **jenkins/ssh-slave** so it can be used from my Jenkins with Azure Container Instances.

Do you know of any android sdk image that is as great as yours and is based on jenkins/ssh-slave? If not, do you think about creating one?

Regards

**Comment by thyrlian** [comment]
Hi @BlackHornet, thanks for the compliment.

This image is already jenkins-ready, no need to based on any other image.

* The SSH server is already [installed and configured](https://github.com/thyrlian/AndroidSDK/blob/master/android-sdk/Dockerfile#L61-L81) in this image
* SSH server will be [automatically launched at the system startup](https://github.com/thyrlian/AndroidSDK/blob/master/android-sdk/supervisord.conf#L7-L10)
* Regarding how to SSH and authorized_keys, please refer to [here](https://github.com/thyrlian/AndroidSDK#ssh)
* To use it as a Jenkins (or whatever CI) slave, either use it directly via ssh (but you have to control the slave lifecycle on your own), or use Docker Plugin.  Examples and how to can be found [here](https://github.com/mytaxi/AndroidCI).
