### ISSUE TITLE
Getting errors when I try to mount sdk

### ISSUE THREAD

**Issue by MalteToenjes** [thyrlian/AndroidSDK#13]
I'm using Ubuntu 18 and I get tons of errors when I try to mount the sdk dir into the container using this command:

> docker run -it --rm -v sdk bash -c 'cp -a $ANDROID_HOME/. /sdk'

Errors:

> cp: read error: I/O error
cp: can't open '/./proc/sys/net/ipv6/route/flush': Permission denied
cp: can't open '/./proc/sys/vm/compact_memory': Permission denied
cp: can't open '/./proc/kmsg': Operation not permitted
cp: can't open '/./proc/sysrq-trigger': Permission denied
cp: read error: I/O error
cp: read error: Invalid argument

Full:
https://pastebin.com/B2mgsf3h

**Comment by thyrlian** [comment]
Hi @MalteToenjes, don't worry, I'll help you out.

You said that you got stuck with this command:

```bash
docker run -it --rm -v sdk bash -c 'cp -a $ANDROID_HOME/. /sdk'
```

I believe that you were trying the step below from [Getting Started](https://github.com/thyrlian/AndroidSDK#getting-started):

> `# copy the pre-downloaded SDK to the mounted 'sdk' director`
> `docker run -it --rm -v $(pwd)/sdk:/sdk thyrlian/android-sdk bash -c 'cp -a $ANDROID_HOME/. /sdk'`

First of all, what exactly does this command do?

At this step, we assume that you've successfully pulled the image from remote docker registry.  But you'll still need to prepare Android SDK packages on your host machine (of course you can also download from [here](https://developer.android.com/studio/#command-tools) - the one for Linux, since the container is Linux based).

Let's break down the command from README:

```console
docker run
# Run a container.
# General form is as below:
docker run [OPTIONS] IMAGE[:TAG|@DIGEST] [COMMAND] [ARG...]

-it
# For interactive processes (like a shell), you must use -i -t together in order to allocate a tty for the container process.

--rm
# Automatically remove the container when it exits.

-v $(pwd)/sdk:/sdk
-v [host-src:]container-dest[:<options>]
# Bind mount a volume.
# The comma-delimited `options` are [rw|ro], [z|Z], [[r]shared|[r]slave|[r]private], and [nocopy].
# The 'host-src' is an absolute path or a name value.
# If neither 'rw' or 'ro' is specified then the volume is mounted in read-write mode.

thyrlian/android-sdk
# This is the IMAGE

bash -c 'cp -a $ANDROID_HOME/. /sdk'
# This is the COMMAND
# Which simply copies the pre-downloaded Android SDK from $ANDROID_HOME to /sdk directory
```

Hope it's clearer after breaking down.  One more time, let's group them together to understand what we wanna achieve here:

`docker run -it --rm -v $(pwd)/sdk:/sdk thyrlian/android-sdk bash -c 'cp -a $ANDROID_HOME/. /sdk'`

The anatomy of a series of actions:

* Launch a container from the pulled image `thyrlian/android-sdk`.
* Mount `$(pwd)/sdk` directory from host (at this moment, it's empty) to container's `/sdk` directory.
* Run command inside container: `cp -a $ANDROID_HOME/. /sdk`, this would copy the pre-downloaded Android SDK (which is located in `$ANDROID_HOME`) to the `/sdk` directory.  Since the `/sdk` directory in the container is actually mounted from `$(pwd)/sdk` on your host machine, after the copying, your host directory `$(pwd)/sdk` will not be empty any more, it will persist the Android SDK, even after the container is terminated.
* After command execution finishes, exit and remove the container.
* Now you have the Android SDK in `$(pwd)/sdk` on your host machine ready.

Finally, compare yours and the command from README:

```bash
# yours
docker run -it --rm -v sdk bash -c 'cp -a $ANDROID_HOME/. /sdk'

# README
docker run -it --rm -v $(pwd)/sdk:/sdk thyrlian/android-sdk bash -c 'cp -a $ANDROID_HOME/. /sdk'
```

* Your volume option `-v` is not correct, it only says `sdk`, while it should be `host-src:container-dest`, so it should be `host-src:/sdk`, and the `host-src` is up to you.
* The mandatory IMAGE argument `thyrlian/android-sdk` is missing, since it's mandatory, seems like docker command takes something else as the IMAGE argument.

Hope you get the idea and solve your problems.

**Comment by MalteToenjes** [comment]
Wow  thank  your  for your detailed answer...I edited the command which looks  like this:

> docker run -it --rm -v /root/sdk:/sdk thyrlian/android-sdk bash -c 'cp -a $ANDROID_HOME/. /sdk'

So I didnt get an error message and the folder /root/sdk contains  now the tools  dir....but I'm confused since  the docker container didn't start. 
And I have one  more question...If i want to create an AVD for the container, do I have to  execute the  command from /root/sdk/tools/bin/avdmanager, since this is mounted into  the container?

**Comment by thyrlian** [comment]
Yes, as explained, the purpose of this command is just to copy Android SDK to your host machine.  You could just follow the steps in README.

WRT AVD, this Docker image contains SSH server.  So after booting up the container, you can ssh to the container (just treat it as a remote machine), then for sure you can execute whatever command you want there.

**Comment by MalteToenjes** [comment]
Hey I still have a problem to  create a avd.
When I run this command:
> /sdk/tools/bin# $ANDROID_HOME/emulator/emulator64-arm -avd test2 -no-window -no-boot-anim -noaudio -accel on -gpu off


I got this error:

> emulator: ERROR: This AVD's configuration is missing a kernel file! Please ensure the file "kernel-qemu" is in the same location as your system image.
emulator: ERROR: ANDROID_SDK_ROOT is defined (/root/sdk) but cannot find kernel file in /root/sdk/system-images/ sub directories

Here are a few more  infos:

> echo $ANDROID_HOME /root/sdk/
echo $ANDROID_SDK_ROOT /root/sdk
echo $PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/root/sdk/tools/:/root/sdk/platform-tools/:/root/sdktools/
ls $ANDROID_HOME/emulator
android-info.txt  emulator        emulator64-crash-service  emulator-check  lib64     NOTICE.txt   qemu      resources
bin64             emulator64-arm  emulator64-x86            lib             mksdcard  package.xml  qemu-img  source.properties

> $ANDROID_HOME/tools/bin/avdmanager list avds
Name: test2
    Path: /root/.android/avd/test2.avd
   Error: Missing system image for Google APIs x86 test2.'

But  I dont rly get the error since kernel-qemu is  there:

> ls $ANDROID_HOME/system-images/android-25/google_apis/armeabi-v7a/
advancedFeatures.ini  build.prop  data  kernel-qemu  kernel-ranchu  NOTICE.txt  package.xml  ramdisk.img  source.properties  system.img  userdata.img

Would be rly nice if you could help me our here again

**Comment by thyrlian** [comment]
* You don't have to go inside any `$ANDROID_HOME` directory such as `emulator` or `tools/bin`, all of them are actually already added to the `PATH` system environment variable, you can check [here](https://github.com/thyrlian/AndroidSDK/blob/master/android-sdk/Dockerfile#L54).

* Please read carefully and strictly follow the [Emulator](https://github.com/thyrlian/AndroidSDK#emulator) section.  Like it says:
> Make sure that the required SDK packages are installed, you can find out by above command.  To install, use the command below.  Whenever you see error complains about `ANDROID_SDK_ROOT`, such as `PANIC: Cannot find AVD system path. Please define ANDROID_SDK_ROOT` or `PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value`, it means that you need to install following packages.

  ```console
  sdkmanager "platform-tools" "platforms;android-<api_level>" "emulator"
  ```

**Comment by MalteToenjes** [comment]
To be  honest I have  never seen the  Emulator section: But I still have  one  problem. I used this command

> emulator64-arm -avd <virtual_device_name> -noaudio -no-boot-anim -no-window -accel on &

and I get this error

> emulator64-arm: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.7' not found (required by emulator64-arm)
emulator64-arm: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by emulator64-arm)
emulator64-arm: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by emulator64-arm)
emulator64-arm: /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5: version `Qt_5' not found (required by emulator64-arm)

It seems I need a newer QT version

> qmake  -version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu

So I downloaded  qt-opensource-linux-x64-5.9.4.run from here https://download.qt.io/official_releases/qt/5.9/5.9.4/  but when  I  try to run I  get   this

> QXcbConnection: Could not connect to display

It seems I cant update qt  this way?

**Comment by MalteToenjes** [comment]
Mhm I've tried the whole README process from scratch and got the same result :( just  for the clarity...I have first to download and install all dependencies like "platform-tools" "platforms;android-23" "emulator" or "system-images;android-23;google_apis;x86" on the sdk dir on the host  machine and after this I can mount it to the container right? So every time I do  an update  in the sdk dir I have tto mount it?

**Comment by thyrlian** [comment]
Hi, after you have the sdk mounted from the host machine to the container, you can do the dependencies / packages installation inside the container, that's no problem :)

**Comment by MalteToenjes** [comment]
I fixed the QT issue and the   emulator  is finally running....I fixed it with those commends

> export QT_QPA_PLATFORM=offscreen
export LD_LIBRARY_PATH=${ANDROID_HOME}/tools/lib64:${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib

But I need a  GUI and I would to connect via VNC so I  pulled the other image and started the docker like this:

> docker run --privilege -d -p 5901:5901 -p 2222:22 -v $(pwd)/docker-sdk:/opt/android-sdk thyrlian/android-sdk-vnc

creating the  avd was no problem...but running it with

> emulator64-x86 -avd test -noaudio -no-boot-anim -gpu swiftshader

gave  me  this  log

> Warning: This plugin does not support setting window masks ((null):0, (null))
INFO: QtLogger.cpp:66: Warning: This plugin does not support setting window masks ((null):0, (null))
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  1 (X_CreateWindow)
  Resource id in failed request:  0x3
  Serial number of failed request:  6
  Current serial number in output stream:  8

I tried also -gpu  host & offscreen...KVM ist  set correctly...

**Comment by thyrlian** [comment]
It used to require `LD_LIBRARY_PATH`, but not any more, as you can see from this merged [PR](https://github.com/thyrlian/AndroidSDK/pull/7/commits/9484b73530a69db36101705e9732b3ce751203cb#diff-ae7ee5ad91f0880eb72276b441d917bcL54)

**Comment by MalteToenjes** [comment]
Finally its working now....I'm not completly why its running now...probably because I installed mesa-utils on host...but not completly sure...
But thanks a lot for your help!

**Comment by thyrlian** [comment]
Good to hear that.  Thanks for letting us know `mesa-utils` solves the problem for your case.  Have fun :)
