### ISSUE TITLE
error ' licences have not been accepted' when running gradlew tests

### ISSUE THREAD

**Issue by eyal919** [thyrlian/AndroidSDK#16]
when trying to run some tests using gradlew i'm getting the next error:
Can anyone please help?
Thanks
> 14:47:51 Checking the license for package Android SDK Build-Tools 28.0.3 in /opt/android-sdk/licenses
14:47:51 Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
14:47:51 Checking the license for package Android SDK Platform 27 in /opt/android-sdk/licenses
14:47:51 Warning: License for package Android SDK Platform 27 not accepted.
14:47:51 
14:47:51 FAILURE: Build failed with an exception.
14:47:51 
14:47:51 * What went wrong:
14:47:51 A problem occurred configuring project ':android-sdk'.
14:47:51 > Failed to install the following Android SDK packages as some licences have not been accepted.
14:47:51      platforms;android-27 Android SDK Platform 27
14:47:51      build-tools;28.0.3 Android SDK Build-Tools 28.0.3
14:47:51   To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
14:47:51   Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
14:47:51   
14:47:51   Using Android SDK: /opt/android-sdk

**Comment by eyal919** [comment]
may related to: https://github.com/thyrlian/AndroidSDK/pull/15

**Comment by thyrlian** [comment]
Hi @eyal919, yes, you're right.  Please wait for the merging of this PR, thank you.

**Comment by thyrlian** [comment]
Fixed by [PR#17](https://github.com/thyrlian/AndroidSDK/pull/17)
