### ISSUE TITLE
Using alternate ARM architecture emulator?

### ISSUE THREAD

**Issue by GVPerry** [thyrlian/AndroidSDK#2]
Hi. I've been using this Docker image today and was successful in getting it running and updating packages etc.

However the APK I am interested in testing only runs on ARM architecture, not x86. I've done the following but can't figure out how to get NoVNC to connect to this new emulator that is running?

```
root@18bb56082245:/# sdkmanager --list --verbose
root@18bb56082245:/# sdkmanager "system-images;android-25;google_apis;armeabi-v7a"
root@18bb56082245:/# echo "no" | avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"
root@18bb56082245:/# avdmanager list avd
Parsing /root/build-tools/27.0.1/package.xmlParsing /root/emulator/package.xmlParsing /root/patcher/v4/package.xmlParsing /root/platform-tools/package.xmlParsing /root/platforms/android-25/package.xmlParsing /root/system-images/android-25/google_apis/armeabi-v7a/package.xmlParsing /root/system-images/android-25/google_apis/x86_64/package.xmlParsing /root/tools/package.xmlAvailable Android Virtual Devices:
    Name: samsung_galaxy_s6_7.1.1
  Device: Samsung Galaxy S6 (User)
    Path: /root/android_emulator
  Target: Google APIs (Google Inc.)
          Based on: Android 7.1.1 (Nougat) Tag/ABI: google_apis/x86_64
---------
    Name: test
    Path: /root/.android/avd/test.avd
  Target: Google APIs (Google Inc.)
          Based on: Android 7.1.1 (Nougat) Tag/ABI: google_apis/armeabi-v7a
root@18bb56082245:/# ./emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on &
root@18bb56082245:/# adb devices
List of devices attached
emulator-5554	device
```

So I think I have successfully installed and launched the ARM emulator, but I can't figure out how to attach that session to the NoVNC console... Does NoVNC spawn inside of the emulator image itself, or is it something in the Docker rc files that runs it?

Thanks in advance

**Comment by thyrlian** [comment]
Thanks for the request.

Don't worry, I'll install the VNC server on the docker image side (not inside the emulator).  Then publish the new image soon this week (either the same image or as a separate image).

**Comment by thyrlian** [comment]
@GVPerry thanks for your patience.  It's finished now and can be used at [`vnc` branch](https://github.com/thyrlian/AndroidSDK/tree/vnc).  But I still need a few more minor tweaks (including updating README).

**Comment by thyrlian** [comment]
I made it into a sub image, coz I don't really recommend using emulator inside container, and also this feature increases the image size for about 200MB.

**Comment by thyrlian** [comment]
@GVPerry feature branch has been merged to master.
