### ISSUE TITLE
How to start a emulator with customized screen size.

### ISSUE THREAD

**Issue by panyang1217** [thyrlian/AndroidSDK#23]
I used the docker to start a emulator, but its screen size is 480x320. How could I start a emulator with another size than 480x320

**Comment by thyrlian** [comment]
To customize an emulator's screen resolution, please check these:

https://stackoverflow.com/questions/43816737/how-to-create-an-android-avd-for-pixel-device-from-command-line/43990123#43990123

https://stuff.mit.edu/afs/sipb/project/android/docs/tools/devices/managing-avds-cmdline.html#CustomDensity
