### ISSUE TITLE
Adding Android SDK platforms in Dockerfile

### ISSUE THREAD

**Issue by gumil** [thyrlian/AndroidSDK#24]
Is it possible to add Android SDK platforms to be added in the dockerfile?
Is it reasonable to put it?

I was just wondering if it could speed up builds if the Android SDKs are already added in the Dockerfile rather than adding them after.

**Comment by gumil** [comment]
> Simply maintain an external persistent SDK directory (including the platform or whatever package needed by your project), and mount it to the container. Please check the README to see how to do it. Furthermore, you can also mount gradle build cache, same approach.

The thing is I'm using the docker image in the CI so the host machine is agnostic to any platform so mounting SDK is not an option. But thanks for clarifying.

**Comment by thyrlian** [comment]
Your CI instance is agnostic, but you can mount an external SDK volume from a static NFS.  You can find more info [here](https://github.com/thyrlian/AndroidSDK#nfs).
