### ISSUE TITLE
‘Jenkins’ doesn’t have label ‘android’

### ISSUE THREAD

**Issue by iMezied** [thyrlian/AndroidSDK#26]
during the Jenkins job execution, the error raised

> ‘Jenkins’ doesn’t have label ‘android’

and here is an error log 

> Error during callback
> com.github.dockerjava.api.exception.BadRequestException: {"message":"OCI runtime create failed: container_linux.go:345: starting container process caused \"process_linux.go:430: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/Users/user/Desktop/master/authorized_keys\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/overlay2/e87c57b43e7a5d998da41741a539ae48a207f42752bd3ab715fb1e65b9d8a434/merged\\\\\\\" at \\\\\\\"/var/lib/docker/overlay2/e87c57b43e7a5d998da41741a539ae48a207f42752bd3ab715fb1e65b9d8a434/merged/root/.ssh/authorized_keys\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"}
> 
> 	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:99)
> 	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
> 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by thyrlian** [comment]
`Jenkins` doesn’t have label `android`

which is due to your creation of `android` slave node (a running Docker container) failed

which is because of:

```console
mounting \\\"/Users/user/Desktop/master/authorized_keys\\\" to rootfs \\\"/var/lib/docker/overlay2/e87c57b43e7a5d998da41741a539ae48a207f42752bd3ab715fb1e65b9d8a434/merged\\\" at \\\"/var/lib/docker/overlay2/e87c57b43e7a5d998da41741a539ae48a207f42752bd3ab715fb1e65b9d8a434/merged/root/.ssh/authorized_keys\\\" caused \\\"not a directory\\\"\""
```

Please double check your mounting volume.

**Comment by iMezied** [comment]
@thyrlian as mentioned in the tutorial 

1- I added the host id_rsa.pub under authorized_keys directory 

2- generated id_rsa.pub key via this command 

> echo 'echo -e "\n" | ssh-keygen -t rsa -b 4096 -N "" -C "root@domain.com"' | docker exec -i jenkins bash
 

3- from Jenkins configuration > container settings Volumes as

> /Users/user/Library/Android/sdk:/opt/android-sdk
> /Users/user/Desktop/aci/authorized_keys:/root/.ssh/authorized_keys 

4- I added the private key that generated under jenkins_home/.ssh/id_rsa as a private key (shall I add the host one instead of this one ?) to connection method > ssh credentials 

Did I do it in the right way?

**Comment by thyrlian** [comment]
I think something went wrong at step 3, that's why you've got such logs.

In the Docker container, the directory path `/root/.ssh/authorized_keys` is correct.

In order to debug, please don't mix with Jenkins yet, just simply launch the container with mounting the volume, to see if it is alright or not.  More details please check [here](https://github.com/thyrlian/AndroidSDK#ssh).

E.g.:
```
docker run -d -p 2222:22 -v /Users/user/Library/Android/sdk:/opt/android-sdk -v /Users/user/Desktop/aci/authorized_keys:/root/.ssh/authorized_keys thyrlian/android-sdk
```

**Comment by thyrlian** [comment]
It might be your host (local) `authorized_keys` is a directory instead of a file, and in container `authorized_keys` is a file.

Please check and make sure that `/Users/user/Desktop/aci/authorized_keys` is a file, and contains your public ssh key (the content of `id_rsa.pub`).
