### ISSUE TITLE
Tools in /opt/android-sdk/tools/bin not executable by non-root user

### ISSUE THREAD

**Issue by bradjones1** [thyrlian/AndroidSDK#28]
During the build process, the tools in `$ANDROID_HOME/tools/bin` are installed but are not marked executable for group or other. Hence, when running this image (for instance, in CI) with a different user, the `sdkmanager` binary is not directly executable.

**Comment by thyrlian** [comment]
Hi Brad, I'd avoid overcomplicating this issue (by adding executable permission to all users of this directory, including future new files, via either `chmod` or `setuid` / `setgid`).

However, as we recommend mounting external persistent Android SDK directory to container, you can simply change the permission (by `chmod`) within the external directory, which would be reflected to container.

Thanks.
