### ISSUE TITLE
Unable to update sdkmanager

### ISSUE THREAD

**Issue by 1995YogeshSharma** [thyrlian/AndroidSDK#30]
I found this project interesting and was trying to install it on my system but I am stuck on an error when trying to update sdk manager-
![Screenshot from 2019-11-15 14-15-14](https://user-images.githubusercontent.com/9693472/68929437-65b2a100-07b2-11ea-908f-343bf5b46a14.png)

I searched a bit online but the solutions given are only for java 9 and 10. I have ubuntu 18.04 and java 11. Is there any other solution apart from downgrading java version?

**Comment by thyrlian** [comment]
You can try to do the `sdkmanager --update` inside a docker container, with the SDK directory mounted from host to the container.
