### ISSUE TITLE
VNC screen size

### ISSUE THREAD

**Issue by ilteoood** [thyrlian/AndroidSDK#33]
Hi,
is it possible to customize the screen size at container boot?

**Comment by thyrlian** [comment]
Hi @ilteoood,

If I'm not mistaken, you could try this `vncserver -geometry 1024x768`.

You can simply append the launch argument [here](https://github.com/thyrlian/AndroidSDK/blob/master/android-sdk/vnc/supervisord_vncserver.conf#L2), and build your own image.
