### ISSUE TITLE
Emulator does not show any graphics

### ISSUE THREAD

**Issue by aerymilts** [thyrlian/AndroidSDK#37]
### Description

Emulator shows black screen

![image](https://user-images.githubusercontent.com/24253983/84159746-fbd84c80-aa9f-11ea-859d-f53e46cb2636.png)

### Steps to reproduce the issue

```bash
$ docker run -it --rm -v $(pwd)/sdk:/sdk thyrlian/android-sdk bash -c 'cp -a $ANDROID_SDK_ROOT/. /sdk'
$ docker run -d -p 59.1: 5901 -p 2222:22 -v $(pwd)/sdk:/opt/android-sdk -v ~/.ssh/emulator.pub:/root/.ssh/authorized_keys -v $(pwd)/sdk_builder.sh:/root/sdk_builder.sh -v $(pwd)/com.amazon.kindle.apk:/root/com.amazon.kindle.apk thyrlian/android-sdk-vnc
$ ssh root@0.0.0.0 -p 2222

root@20448ea13e96:$ bash sdk_builder.sh
```
I've also tried toggling various gpu options and different system images to no avail.

```bash
# sdk_builder.sh

sdkmanager --update
sdkmanager "platform-tools" "platforms;android-24" "platforms;android-25" "emulator"
sdkmanager "system-images;android-24;default;armeabi-v7a"
sdkmanager "system-images;android-25;google_apis;armeabi-v7a"

export QTWEBENGINE_DISABLE_SANDBOX=1

echo 'no' | avdmanager create avd -n 24_test -k "system-images;android-24;default;armeabi-v7a"
echo 'no' | avdmanager create avd -n 25_test -k "system-images;android-25;google_apis;armeabi-v7a"
# INFO: List existing Android Virtual Devices
avdmanager list avd
# launch emulator
 emulator -avd 24_test -no-audio -no-boot-anim -gpu off
# emulator -avd 24_test -no-audio -no-boot-anim -accel on -gpu swiftshader_indirect &

```

The output looks like that
![image](https://user-images.githubusercontent.com/24253983/84161293-b452c000-aaa1-11ea-9e4f-0b711c4e3b58.png)

But rerunning the script a second time round gives just this, without the 'emulator out of date' output
![image](https://user-images.githubusercontent.com/24253983/84161564-faa81f00-aaa1-11ea-87a4-dbd6ed57e9f3.png)

### Describe the results you expected

The ability to use the emulator through VNC visually.

**Comment by thyrlian** [comment]
Hi @aerymilts, I'm currently in the hospital and will check this once I'm back home.

In general, I've tested the container on my side before publishing it, I can view the emulator, interact with the emulator via mouse, and also run UI test on the emulator.

BTW, the warning you've got is not a big deal, you can totally ignore that.

Another matter is, virtualizing an ARM-based emulator, inside a docker container is a quite expensive action, for sure it will be slow.  It may take even a few minutes before the real Android screen gets rendered properly.

I'll try to reproduce using the steps you've provided, and share the updates here.

**Comment by aerymilts** [comment]
Hey @thyrlian, I'm sorry to hear that you're in hospital. I hope you get well soon.

I've tried leaving the emulator to start and render for up to half an hour at a time but nothing shows up. 

Not sure if this bit of information helps, but I have also tried installing packages from the container and that didn't work. I'm wondering if this is a sign that the emulator hasn't booted properly.

```bash
root@20448ea13e96:$ adb install com.amazon.kindle.apk
Performing Streamed Install
adb: failed to install com.amazon.kindle.apk: Can't find service: package
```

As a thought, would running dind (Docker in Docker) allow for virtualizing an x86-based emulator instead? I intend to use the emulator to use apps that have better support on mobile vs desktop.

I didn't say this the first time round, but _fantastic_ job on this repository and the support you're providing. I saw the level of details you were providing (and spelling out, in some cases) in the other resolved issues. 👍

**Comment by thyrlian** [comment]
Thank you @aerymilts for your acknowledgement and good wishes.  I'm getting better now so I've played a bit.

By following the same steps you've listed, I'm able to launch the emulator and interact with it as well.

And I've tried both of the rendering options below, none of them has a problem.

```shell
emulator -avd 24_test -no-audio -no-boot-anim -gpu off &
emulator -avd 24_test -no-audio -no-boot-anim -accel on -gpu swiftshader_indirect &
```

As I said before, the virtualization inside Docker container is quite expensive, the bootup (readiness) of the emulator may take some minutes, which varies between machines (for instance: MacMini is way faster than MacbookPro).  In fact, on my MacbookPro I haven't been waiting too long.  And the other error message you've given - `Can't find service: package` tells that the bootup process is not finished yet (or properly).  My suggestion would be: try with a powerful machine or some cloud service.  Please forget about Docker in Docker, it won't help.

<img width="1092" alt="VNC 1" src="https://user-images.githubusercontent.com/352956/84866823-8c072a80-b07a-11ea-99c7-037dab8dc511.png">
<img width="1092" alt="VNC 2" src="https://user-images.githubusercontent.com/352956/84866832-90334800-b07a-11ea-9a43-fd174b535e60.png">

**Comment by aerymilts** [comment]
Hey @thyrlian, appreciate you testing out my scripts on your setup. Good to know I've set it up correctly and it's just down to the hardware. It appears that my GPU is not shared with the container. I managed to get the emulator going by [disabling](https://support.apple.com/en-us/HT202043) automatic graphics switching. The interface is incredibly slow, as you've pointed out before.

Re: dind, I just went over the [Emulator](https://github.com/thyrlian/AndroidSDK#emulator) section again. Does this mean that there's _absolutely_ no way for a Mac user to run x86 emulators (short of dual booting into Linux)? I did find that there are paid options out there that enabled [nested virtualization](https://stackoverflow.com/a/49815500) but it seems like there's not much support for this. 

I don't have any knowledge in this area - do you have any recommendations/thoughts?

**Comment by thyrlian** [comment]
Hi @aerymilts, it's really good to hear that now it works for you after your magic tweak on your host machine.  I'd like to copy the screenshot here from the link you've given, for other users' reference, because Apple moves its "permalink" often.  Actually this is something new to me since my MacbookPro only has an integrated graphic card, I don't even have such option (meaning the performance on my machine should be worse than yours, still I'm able to run UI test under acceptable timing).

<img width="640" alt="yosemite-system-prefs-energy-saver-automatic-graphics-switching-disable" src="https://user-images.githubusercontent.com/352956/84986028-1d8ba080-b13e-11ea-8566-a4e49671d5eb.png">

Regarding dind:
* In general, it's not possible on macOS.  However, it's not absolutely impossible, if you can manage to port KVM to macOS, plus a ton of hacks, it may work, probably that doesn't worth the effort.
* Yes, not long ago VirtualBox started to support nested virtualization, [gradually from AMD CPU to Intel CPU](https://stackoverflow.com/a/55296222/1083611).
* Ultimately, I would pay more attention to the intention rather than the solution. We could get it working in some way, but in the end, the performance won't make us satisfied.  For the sake of debugging, or just playing around, the simplest solution would be the Intel x86 emulator which comes with Android Studio.  The emulator inside a Docker container is designed for CI purpose, for UI test automation.  And usually, the companies have powerful Linux machine on-premises, or pay some cloud computing services, there the support for x86 emulator inside Docker container is optimal.  What do you think?

**Comment by aerymilts** [comment]
@thyrlian, go for it. I hope this is helpful for someone else in the future as well. 😄 That's interesting. I think the reason why it doesn't work on my integrated graphics is because I have a bad habit of leaving my laptop on for weeks at a time, so there's usually resource leaks which doesn't work very well for high performing apps. For reference, here are the stats of my MBP
![image](https://user-images.githubusercontent.com/24253983/85143036-cc81c680-b27b-11ea-9970-9ca2070273c7.png)
>- In general, it's not possible on macOS. However, it's not absolutely impossible, if you can manage to port KVM to macOS, plus a ton of hacks, it may work, probably that doesn't worth the effort.
>- Yes, not long ago VirtualBox started to support nested virtualization, gradually from AMD CPU to Intel CPU.

Thanks for sharing, that's where I ended up as I went down the rabbit hole. I'm pretty much stuck as virtualization and architectures is way out of depth for me.

>- Ultimately, I would pay more attention to the intention rather than the solution. We could get it working in some way, but in the end, the performance won't make us satisfied. For the sake of debugging, or just playing around, the simplest solution would be the Intel x86 emulator which comes with Android Studio. The emulator inside a Docker container is designed for CI purpose, for UI test automation. And usually, the companies have powerful Linux machine on-premises, or pay some cloud computing services, there the support for x86 emulator inside Docker container is optimal. What do you think?

My intent is to build an emulator that allows me to use mobile apps that requires low to moderate resources (think: smooth paging for Kindle for Android on an emulator), using open source tools, high reproducibility (container as code) and is easy to port across OSes. That's how I got to Docker and your project.

I also came across [BlueStacks](https://www.bluestacks.com/) which serves my purpose pretty well (in fact it seems like it's meant for high performance mobile gaming). It's just that it's not open source and it doesn't have high configurability. I initially thought that I'd just have to go deeper into Docker to find the right setup to get it to work just like how BlueStacks does it. But it seems like there are limitations with Docker that just doesn't allow it. Is my understanding accurate?

**Comment by aerymilts** [comment]
> For the sake of debugging, or just playing around, the simplest solution would be the Intel x86 emulator which comes with Android Studio.

I just realised, did you mean to say that using the x86 emulator with Android Studio natively on my MBP would work?

**Comment by thyrlian** [comment]
For my integrated graphics card, I also tend to leave my laptop running/hibernating for weeks, but I haven't run into any problem launching emulator inside a container.

I got your purpose now, and I don't think emulator in container is a good solution for you.  Please go and give a try of the x86 emulator from Android Studio, that should serve your needs.

**Comment by aerymilts** [comment]
Sorry for the late response. Yes, it seems that accelerated containerised emulation for Mac is a convoluted solution at best. Thank you for helping me with this!
