### ISSUE TITLE
Use an error in the Jenkins Pipeline

### ISSUE THREAD

**Issue by DreamPWJ** [thyrlian/AndroidSDK#48]
docker {
                            // android sdk环境  构建完成自动删除容器
                            image "thyrlian/android-sdk:latest"
                            // 缓存gradle工具  :ro或者 :rw 前者表示容器只读，后者表示容器对数据卷是可读可写的。默认情况下是可读可写的
                            args " -v /var/cache/gradle:/root/.gradle:rw -v /my/android/sdk:/opt/android-sdk:ro "
                            reuseNode true // 使用根节点
                        }

13:49:49  Warning: License for package Android SDK Platform 28 not accepted.
13:49:49  
13:49:49  FAILURE: Build failed with an exception.
13:49:49  
13:49:49  * What went wrong:
13:49:49  Could not determine the dependencies of task ':accesscontrol:compileReleaseJavaWithJavac'.
13:49:49  > Failed to install the following Android SDK packages as some licences have not been accepted.
13:49:49       patcher;v4 SDK Patch Applier v4
13:49:49       build-tools;28.0.3 Android SDK Build-Tools 28.0.3
13:49:49       platform-tools Android SDK Platform-Tools
13:49:49       tools Android SDK Tools
13:49:49       platforms;android-28 Android SDK Platform 28
13:49:49       emulator Android Emulator
13:49:49    To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
13:49:49    Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
13:49:49    
13:49:49    Using Android SDK: /opt/android-sdk

**Comment by DreamPWJ** [comment]
-v /my/android/sdk:/opt/android-sdk:ro   not work

**Comment by thyrlian** [comment]
There are two things according to your log:

* You need to accept some license, please read [here](https://github.com/thyrlian/AndroidSDK#accepting-licenses).
* If you need to install certain Android SDK package, you should either install it via command line on your host machine (where you persist the Android SDK directory), or update it inside the container without using `ro` flag.  You should be able to find all information from the README.
