### ISSUE TITLE
android:text="@{`$`   Packaging appears to become.  ????  Abnormal display

### ISSUE THREAD

**Issue by DreamPWJ** [thyrlian/AndroidSDK#49]
android:text="@{`$`+TicketDetailsViewModel.coupon.saleNum}"   Pack the local computer normally

**Comment by DreamPWJ** [comment]
android:text="@{`已售`+TicketDetailsViewModel.coupon.saleNum}"

**Comment by thyrlian** [comment]
Hi @DreamPWJ, this Docker image does nothing related to compiling or packing, that's what Android SDK does, thus not an issue here.

From what you've described, the behavior is similar to what I've mentioned [here](https://speakerdeck.com/thyrlian/android-meets-docker-1?slide=18).

Again, it seems like an encoding problem, please check how those files are saved locally (if you try on a different clean machine, I believe the issue would occur as well).  Furthermore, you'll find an answer from stackoverflow of the problem you've described.  Good luck.
