### ISSUE TITLE
Why do we need to remove X11 in watchdog.sh

### ISSUE THREAD

**Issue by StanlyT** [thyrlian/AndroidSDK#52]
Hello Thyrlian,

First of all thank You very much for all Your efforts related with current project. Could you explain please why do we need to remove X11, i mean instructions in watchdog.sh
```
 rm -fv /tmp/.X*-lock >> $log_file
 rm -fv /tmp/.X11-unix/* >> $log_file
```
Thank You!

**Comment by thyrlian** [comment]
Hi @StanlyT.

You can find the original commit for that piece of code [here](https://github.com/thyrlian/AndroidSDK/commit/7678f684eca19af2e122d57f82b0c0e5693737f0).

So the purpose of it was for "**_Add clean up script for vnc when receiving SIGTERM_**" according to the commit message.  More details, the concrete problem and the solution are available on [stackoverflow](https://stackoverflow.com/questions/51633643/docker-vnc-2nd-time-connect-issue).

Is this solution causing any problem for you?  Thanks :)

**Comment by StanlyT** [comment]
About causing problem i'm not sure. I have to recheck that. Thanks a lot for Your answer!
