### ISSUE TITLE
Think over support JDK 20+ on your docker image ?

### ISSUE THREAD

**Issue by Break4ever** [thyrlian/AndroidSDK#74]
According to [release note](https://docs.gradle.org/8.4/release-notes.html)

Since Gradle 8.3+, Gradle start to supports running on Java 20, even in Gradle 8.4 also supports Java 21.

I am not sure as my perspective, docker image can use JDK 21 and also compatible for Android JDK 17 based project ?

cc @thyrlian

**Comment by thyrlian** [comment]
Hi @Break4ever, thanks for reporting this.

Actually when developing Android apps, it's advisable to use the JDK version recommended by Google for the targeted Android API level.

Gradle's support for a particular Java version is primarily related to the Java code writen in your Gradle build scripts or other non-Android parts in your project.  It allows you to use new Java features and enhancements in your build scripts while building your Android app.

Thus, there is no action to take at this moment.  Thank you again.

**Comment by Break4ever** [comment]
Thanks for your reply !
