### ISSUE TITLE
ARM64 image variant

### ISSUE THREAD

**Issue by wakawaka54** [thyrlian/AndroidSDK#75]
Is there any reason why you aren't building an ARM64 based image variant? With Apple Silicon and AWS Graviton, android developers are more likely to be developing on an ARM based toolchain.

**Comment by thyrlian** [comment]
Thanks for the suggestion.
Technically, a linux/amd64 image could also run on a Apple M* machine.  But you're right, better to build a dedicated image for the sake of performance.

**Comment by thyrlian** [comment]
Basically we just need to build it with `docker buildx build --platform linux/amd64,linux/arm64`

**Comment by wakawaka54** [comment]
Yeah you might need to check if there is anything incompatible with arm in the current build.

Not sure about some of that i386 stuff. And then it looks like the `JAVA_HOME` variable is set to an amd specific location.

**Comment by thyrlian** [comment]
Some checks and heads-up by ChatGPT:

> Here is the compatibility information for the specific tools and libraries mentioned in your Dockerfile for ARM64 architecture:
> 
> **OpenJDK**: OpenJDK is compatible with ARM64. Microsoft provides a port of OpenJDK for Windows on ARM64 devices​​. Oracle also supports 64-bit ARM systems with Oracle JDK 15 and later versions​​. Microsoft's build of OpenJDK offers LTS binaries for Java 11 and Java 17 on ARM64 for Linux and Windows​​​​.
> 
> **Gradle**: Gradle is compatible with ARM64. The Gradle documentation indicates that any fully supported version of Java can be used with Gradle, which includes ARM64 compatible versions of Java​​. Gradle has also been updated to support running on ARM64 Windows​​. Android's documentation also suggests that Gradle, used via Android Studio or from the command line, supports ARM64 architectures​​​​.
> 
> **Kotlin**: Kotlin's compatibility with ARM64 seems to be in active development. A GitHub issue was opened requesting support for Linux ARM32 and ARM64, indicating ongoing efforts to expand Kotlin's compatibility with these architectures​​​​​​.
> 
> **Android SDK**: The Android SDK supports ARM64. Apps published on Google Play are required to support 64-bit architectures, and if an app is written in Java or Kotlin, it inherently supports 64-bit devices​​​​. Popular game engines used with the Android SDK, such as Unreal, Cocos2d, and Unity, have supported 64-bit since at least 2015-2018​​.
> 
> **Libraries** (libncurses5, libc6, libstdc++6): These libraries are compatible with ARM64. The libncurses5 package is available for ARM64 in Ubuntu 20.04 LTS​​​​. For running 32-bit applications on 64-bit systems, including ARM64, the 32-bit versions of these libraries (e.g., libc6:i386) can be installed​​​​.
> 
> In summary, the major components of your Dockerfile, such as OpenJDK, Gradle, Kotlin, and the Android SDK, as well as the libraries libncurses5, libc6, and libstdc++6, are compatible with ARM64 architecture. However, it's important to ensure that you are using the appropriate versions of these tools and libraries that support ARM64. Additionally, while Kotlin's compatibility is being developed, it's advisable to check the latest status or test it in an ARM64 environment.

**Comment by thyrlian** [comment]
The previous multiarch support (adding i386 architecture) can't be built on ARM64 host machine.  I added that specifically to support the former Android emulators.

```bash
apt-get install -y --no-install-recommends libncurses5:i386 libc6:i386 libstdc++6:i386 lib32gcc-s1 lib32ncurses6 lib32z1 zlib1g:i386
```

The error log I got during the image building process:
```shell
Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/jammy/restricted/binary-i386/Packages  404  Not Found
Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/jammy-updates/main/binary-i386/Packages  404  Not Found
Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/jammy-backports/universe/binary-i386/Packages  404  Not Found
Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/jammy-security/universe/binary-i386/Packages  404  Not Found
```

But according to the [release notes for Android Emulator](https://developer.android.com/studio/releases/emulator#emulator_for_arm64_hosts), starting from August 16, 2020, it should also work from x86_64 to arm64 hosts.  I shall give a try.

**Comment by thyrlian** [comment]
Apologies @wakawaka54 for having to pause my efforts on supporting arm64 for now.

The reason is, it's not just about ensuring all dependencies and libraries in the image work, we also need to make certain Android SDK tools (like `AAPT2`) compatible with arm64 Linux.  The challenge is that Google's pre-built binaries are typically for x86 or x86_64 architectures, **meaning we'd need to build every tool from source for all versions**.  That's a substantial amount of work.  I'm going to put my progress on hold and might revisit this when Google provides better support for arm64 in the future.
