### ISSUE TITLE
[BUG] Could not load the Qt platform plugin "xcb" in "/opt/android-sdk/emulator/lib64/qt/plugins"

### ISSUE THREAD

**Issue by jacky-mb** [thyrlian/AndroidSDK#76]
**Deploy step**
- docker build -t android-sdk:latest .
- docker stop sdk && docker rm sdk
- docker run -d -p 2222:22 -v $(pwd)/sdk:/opt/android-sdk --name sdk --privileged --device /dev/kvm android-sdk:latest
- docker exec -it sdk bash -c 'sdkmanager "emulator" "platform-tools" "platforms;android-34-ext10"'
- docker exec -it sdk bash -c 'sdkmanager --install "system-images;android-34;google_apis;x86_64"'
- docker exec -it sdk bash -c 'yes | sdkmanager --licenses'
- docker exec -it sdk bash -c 'echo "no" | avdmanager create avd -n test -k "system-images;android-34;google_apis;x86_64"'
- docker exec -it sdk bash -c "emulator -list-avds"
- docker exec -d sdk bash -c "emulator -avd test -no-snapshot -no-boot-anim -wipe-data &"
**Issue**
root@8155cdbac042:/# emulator -avd test
INFO    | Storing crashdata in: /tmp/android-unknown/emu-crash-34.1.20.db, detection is enabled for process: 338
INFO    | Android emulator version 34.1.20.0 (build_id 11610631) (CL:N/A)
INFO    | Found systemPath /opt/android-sdk/system-images/android-34/google_apis/x86_64/
INFO    | Storing crashdata in: /tmp/android-unknown/emu-crash-34.1.20.db, detection is enabled for process: 338
INFO    | Duplicate loglines will be removed, if you wish to see each individual line launch with the -log-nofilter flag.
INFO    | Increasing RAM size to 2048MB
WARNING | File System is not ext4, disable QuickbootFileBacked feature
WARNING | could not find /usr/share/zoneinfo/ directory. unable to determine host timezone
INFO    | Warning: could not connect to display  ((null):0, (null))
INFO    | Info: Could not load the Qt platform plugin "xcb" in "/opt/android-sdk/emulator/lib64/qt/plugins" even though it was found. ((null):0, (null))
Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
 ((null):0, (null))
INFO    | Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
 ((null):0, (null))
[347:347:20240404,172832.955062:ERROR elf_dynamic_array_reader.h:64] tag not found
[347:347:20240404,172832.955125:ERROR elf_dynamic_array_reader.h:64] tag not found
Aborted (core dumped)
@thyrlian JangLi. Can you help me to check it?

**Comment by thyrlian** [comment]
Hi @jacky-mb, I'm not sure if you're just too busy to respond.  If that's not the case, I'm disappointed that some people only ask for help here but never contribute back, not even to clarify if it was a false alarm or if a solution was found.
