### ISSUE TITLE
Upgrade To Latest Ubuntu LTS

### ISSUE THREAD

**Issue by mcmah309** [thyrlian/AndroidSDK#78]
Currently the image is built off `ubuntu:22.04`. This should be upgraded to the latest Ubuntu LTS `ubuntu:24.04`. 

(Not a `bug` but unable to create another type of issue)

**Comment by thyrlian** [comment]
The current base image is `ubuntu:22.04`, and you’re suggesting an upgrade to `ubuntu:24.04`, I totally understand the point.  Whilst both are LTS versions, with ***22.04*** supported until ***June 2027*** and ***24.04*** until ***June 2029***, I don’t see an urgent need to upgrade at this time.

The new version, 24.04, brings some changes, but for our use case, particularly in headless mode for Android building, there aren’t significant benefits (as far as I can see, but my knowledge for 24.04 is quite limited).  Additionally, I’ve experienced some issues with 24.04 on one of my personal computer, such as restrictions on unprivileged namespaces, which causes some issue to the Docker Desktop application.

However, we will eventually need to upgrade to the next LTS. I’ll review the PR to see what can be done.

Thank you.

Please let me know if this addresses your concern.

**Comment by mcmah309** [comment]
Packages keep going out of sync with requirements of other projects for us. It's starting to effect our development. We'd rather not fork if we can avoid it, but it's starting to become a necessity on our end.

**Comment by thyrlian** [comment]
Hi Henry, thank you for the explanation.  Do you mind providing any examples (of packages/dependencies)?  Thanks.

**Comment by mcmah309** [comment]
We need cmake 3.26+, a few others like protoc and node, not sure off those versions off the top of my head.

**Comment by thyrlian** [comment]
@mcmah309 please check all my comments in the PR, especially the [last one](https://github.com/thyrlian/AndroidSDK/pull/80#issuecomment-2241776848), if you can help test that in your local machine with your Android project?  Thanks in advance.

**Comment by mcmah309** [comment]
I built the image locally, applied our dev environment on top, and ran a flutter/android app. I had to upgrade our gradle version (as expected) but other than that everything is working seamlessly :+1:
