### ISSUE TITLE
MacOS error when starting emulator

### ISSUE THREAD

**Issue by AndreSand** [thyrlian/AndroidSDK#8]
I followed [Getting Started ](https://github.com/thyrlian/AndroidSDK#getting-started), I entered below commands and I get below error:
$docker pull thyrlian/android-sdk
$docker run -it --rm -v $(pwd)/sdk:/sdk thyrlian/android-sdk bash -c 'cp -a $ANDROID_HOME/. /sdk'
$docker pull thyrlian/android-sdk-vnc
$docker run -it -p 5901:5901 -v $(pwd)/sdk:/opt/thyrlian/android-sdk thyrlian/android-sdk-vnc /bin/bash
$sdkmanager "system-images;android-24;default;armeabi-v7a"
$echo "no" | avdmanager create avd -f -n test -k "system-images;android-24;default;armeabi-v7a" 
$emulator -avd test -noaudio -no-boot-anim -no-window -accel on &

error:
```
[1] 123
root@808e0a565ad9:/# ERROR: 32-bit Linux Android emulator binaries are DEPRECATED, to use them
       you will have to do at least one of the following:

       - Use the '-force-32bit' option when invoking 'emulator'.
       - Set ANDROID_EMULATOR_FORCE_32BIT to 'true' in your environment.

       Either one will allow you to use the 32-bit binaries, but please be
       aware that these will disappear in a future Android SDK release.
       Consider moving to a 64-bit Linux system before that happens.

```

$emulator -avd test -noaudio -no-boot-anim -no-window -force-32bit -accel on &
error:
```
[1] 434
root@27a7d06b1601:/# [139687693248320]:ERROR:./android/qt/qt_setup.cpp:28:Qt library not found at ../emulator/lib/qt/lib
Could not launch '../emulator/qemu/linux-x86/qemu-system-armel': No such file or directory

[1]+  Exit 2                  emulator -avd test -noaudio -no-boot-anim -no-window -force-32bit -accel on
```

I'm new to docker :) 
Thanks.

**Comment by thyrlian** [comment]
Hi @AndreSand, thanks for your reporting.

* With the commands you've fired, this one below has mounted the volume to the wrong destination:
```bash
docker run -it -p 5901:5901 -v $(pwd)/sdk:/opt/thyrlian/android-sdk thyrlian/android-sdk-vnc /bin/bash
```
Which should be like this:
```bash
docker run -it -p 5901:5901 -v $(pwd)/sdk:/opt/android-sdk thyrlian/android-sdk-vnc /bin/bash
# /opt/android-sdk is the $ANDROID_HOME directory
```

* The rest of the commands have no problem, but the root cause of this issue is that you're missing some required SDK packages.  I just updated the README file, please check [here](https://github.com/thyrlian/AndroidSDK#how-to-run-emulator) (previously I made the assumption that you have a complete SDK installation):
> Make sure that the required SDK packages are installed, you can find out by above command.  To install, use the command below.  Whenever you see error complains about `ANDROID_SDK_ROOT`, such as `PANIC: Cannot find AVD system path. Please define ANDROID_SDK_ROOT` or `PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value`, it means that you need to install following packages.
> ```console
> sdkmanager "platform-tools" "platforms;android-<api_level>" "emulator"
> ```

Good luck, please tell me if it solves your problem.  Thanks :)

**Comment by thyrlian** [comment]
BTW, in your case, it should be:
‘’’console
sdkmanager "platform-tools" "platforms;android-24" "emulator"
‘’’

**Comment by AndreSand** [comment]
@thyrlian Thanks a lot for your help! With your above solution I'm able to create and launch emulator :)

**Comment by AndreSand** [comment]
I'm I try to open VNC Viewer 0.0.0.0:5901, I get error "The connection closed unexpectedly". Which VNC Viewer do you use? Maybe I'm missing a command? Thanks :)

**Comment by AndreSand** [comment]
My steps:
A.  Pull the images
$docker pull thyrlian/android-sdk
$docker pull thyrlian/android-sdk-vnc
$docker run -it --rm -v $(pwd)/sdk:/sdk thyrlian/android-sdk bash -c 'cp -a $ANDROID_HOME/. /sdk'
$docker run -it -p 5901:5901 -v $(pwd)/sdk:/opt/android-sdk thyrlian/android-sdk-vnc /bin/bash
B. Now  inside container: Install android emulator components
-root@8d82dff4ccda:/# sdkmanager "platform-tools" "platforms;android-24" "emulator"
-root@8d82dff4ccda:/# avdmanager create avd -n emuTest -k "system-images;android-24;default;armeabi-v7a"
-root@8d82dff4ccda:/# emulator -avd emuTest -noaudio -no-boot-anim -no-window -accel on &

C. Open Vnc Viewer, 0.0.0.0:5901
I get connection error "The connection closed unexpectedly"

**Comment by AndreSand** [comment]
I'm able to see the emulator if I install android emulators components from inside the containers terminal.

My steps:
A.  Pull the images
$docker pull thyrlian/android-sdk
$docker pull thyrlian/android-sdk-vnc
$docker run -it --rm -v $(pwd)/sdk:/sdk thyrlian/android-sdk bash -c 'cp -a $ANDROID_HOME/. /sdk'
$docker run -d -p 5901:5901 -p 2222:22 -v $(pwd)/sdk:/opt/android-sdk thyrlian/android-sdk-vnc /bin/bash

B. Open Vnc Viewer, 0.0.0.0:5901
password: android

Inside container, open terminal and enter below commands
*root@8d82dff4ccda:/#* sdkmanager "platform-tools" "platforms;android-24" "emulator"
*root@8d82dff4ccda:/#* avdmanager create avd -n emuTest -k "system-images;android-24;default;armeabi-v7a"
*root@8d82dff4ccda:/#* emulator -avd emuTest -noaudio -no-boot-anim -no-window -gpu off

C. Emulator runs successfully.

**Comment by thyrlian** [comment]
Exactly, I just updated the README again.

The `vncserver` won't get started if you spin up a container with interactive session.  Because the [supervisor conf file](https://github.com/thyrlian/AndroidSDK/blob/master/android-sdk/vnc/supervisord_vncserver.conf) won't get loaded (instead, you ask to start `/bin/bash`).  It would work if the container is spawned in detached mode.

So, should be like this:

```console
docker run -d -p 5901:5901 -p 2222:22 -v $(pwd)/sdk:/opt/android-sdk -v <YOUR_AUTHORIZED_KEYS_FILE_PATH>:/root/.ssh/authorized_keys thyrlian/android-sdk-vnc
```

I use the built-in `Screen Sharing` application on macOS.

```console
vnc://0.0.0.0:5901
# or
vnc://127.0.0.1:5901
# or
vnc://localhost:5901
```

Thanks again and have fun :)

**Comment by AndreSand** [comment]
Awesome! Thanks for your steps, it's working now :)

**Comment by AndreSand** [comment]
I'm not able to see the device when I do $adb devices. I'm following your [steps](https://github.com/thyrlian/AndroidSDK#access-the-emulator-from-outside) 

I start container with
```docker run -d -p 5901:5901 -p 2222:22 -v $(pwd)/sdk:/opt/android-sdk -v /Users/asandoval/.ssh/id_rsa.pub:/root/.ssh/authorized_keys thyrlian/android-sdk-vnc```

Do I need to change 5901:5901 to 5037:5037?

**Comment by thyrlian** [comment]
Yes, you have to add `-p 5037:5037`, though it's already defined [here](https://github.com/thyrlian/AndroidSDK/blob/master/android-sdk/Dockerfile#L59).  Otherwise it won't bind to the container's IP address and port.

You can find the difference by running `docker ps -a`.
```bash
# without "-p 5037:5037"
PORTS
5037/tcp

# with "-p 5037:5037"
PORTS
0.0.0.0:5037->5037/tcp
```

Other than that, it's important, as mentioned in README:
> Make sure that your **adb client** talks to the **adb server** inside the container, instead of the local one on the host machine. This can be achieved by running `adb kill-server` (to kill the local server if it's already up) before firing `adb connect` command above.

Here are the differences:
```bash
# when listening to local adb server
adb devices
#=> List of devices attached
#=> * daemon not running; starting now at tcp:5037
#=> * daemon started successfully

# when listening to the container's adb server
adb connect 0.0.0.0:5037
#=> * daemon not running; starting now at tcp:5037
#=> * daemon started successfully
#=> connected to 0.0.0.0:5037
```

**Comment by AndreSand** [comment]
Thanks @thyrlian !! it's working :)

I wrote this medium post so I can remember the steps to get the emulator running.
https://medium.com/@AndreSand/android-emulator-on-docker-container-f20c49b129ef
