### ISSUE TITLE
My host machine supports KVM but after I run the docker image, the docker container does not support it?

### ISSUE THREAD

**Issue by Pezhin** [thyrlian/AndroidSDK#9]
Hi, on my CentOS machine, I run `emulator-check`, I got

```
accel:
0
KVM (version 12) is installed and usable.
accel
```

However, when I run `emulator-check` in the docker container, I got
```
accel:
8
/dev/kvm is not found: VT disabled in BIOS or KVM kernel module not loaded
accel
```

And I cannot run x86_64 emulator, can you help me with this?

**Comment by thyrlian** [comment]
Hi @Pezhin, it's exactly as the log said, you should try either of below:
* Enable VT (Virtualization Technology) in BIOS settings
* Load KVM module on the host: `modprobe kvm_intel`

**Comment by Pezhin** [comment]
Hi @thyrlian , I think on my host machine, the KVM module is already loaded but after I run the docker container, the kvm is not enabled in the docker container.

Any idea how I can fix this?

**Comment by Pezhin** [comment]
@thyrlian I re-read the doc and found that 
`docker run -it --privileged -v $(pwd)/sdk:/opt/android-sdk:ro thyrlian/android-sdk /bin/bash`
the `privileged` is needed and also, we have to volume`/dev/kvm`.

I can run the emulator via this command
`docker run -d --privileged -v /dev/kvm:/dev/kvm  -p 5901:5901 -p 2222:22 -p 5037:5037 -v /root/:/opt/android-sdk thyrlian/android-sdk-vnc`

**Comment by thyrlian** [comment]
Congratulations, so everything is fine now?

**Comment by Pezhin** [comment]
@thyrlian yes. It runs very slowly tho but it runs. I will close the issue for u

**Comment by thyrlian** [comment]
Weird, the reason to use x86 emulator is because of its performance.  Don't get it why it's slow on your machine?  Can you maybe try with a different host machine?  Or try to increase the [CPU share constraint](https://docs.docker.com/engine/reference/run/#cpu-share-constraint) and [memory constraints](https://docs.docker.com/engine/reference/run/#user-memory-constraints)?
